parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'


  App\Shared\Infrastructure\SynchronousCommandBus:
    calls:
      - map: [ 'App\WalletManagement\Application\Command\CreateWalletCommand', '@wallet.command.create.handler' ]
      - map: [ 'App\WalletManagement\Application\Command\IncreaseBalanceCommand', '@wallet.command.increase_balance.handler' ]
      - map: [ 'App\WalletManagement\Application\Command\DecreaseBalanceCommand', '@wallet.command.decrease_balance.handler' ]

  wallet.command.create.handler:
    class: App\WalletManagement\Application\Command\CreateWalletHandler
    arguments:
      $balanceFactory: '@wallet.management.balance_factory'

  wallet.command.increase_balance.handler:
    class: App\WalletManagement\Application\Command\IncreaseBalanceHandler
    arguments:
      $operationFactory: '@wallet.management.operation_factory'

  wallet.command.decrease_balance.handler:
    class: App\WalletManagement\Application\Command\DecreaseBalanceHandler
    arguments:
      $operationFactory: '@wallet.management.operation_factory'

  App\Shared\Infrastructure\BasicQueryBus:
    calls:
      - map: [ 'App\WalletManagement\Application\Query\FindAllWalletsQuery', '@wallet.query.find_all.handler' ]
      - map: [ 'App\WalletManagement\Application\Query\GetBalanceQuery', '@wallet.query.get_balance.handler' ]
      - map: [ 'App\WalletManagement\Application\Query\GetWalletQuery', '@wallet.query.get_wallet.handler' ]

  wallet.query.find_all.handler:
    class: App\WalletManagement\Application\Query\FindAllWalletsHandler

  wallet.query.get_balance.handler:
    class: App\WalletManagement\Application\Query\GetBalanceHandler

  wallet.query.get_wallet.handler:
    class: App\WalletManagement\Application\Query\GetWalletHandler

  wallet.management.operation_factory:
    class: App\WalletManagement\Domain\Operation\OperationFactory

  wallet.management.balance_factory:
    class: App\WalletManagement\Domain\Balance\BalanceFactory
