parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'


  command_bus:
    class: App\Shared\Infrastructure\SynchronousCommandBus
    arguments: [ ],
    calls:
      - map: [ 'App\WalletManagement\Application\Command\CreateWalletCommand', '@wallet.command.create.handler' ]


  wallet.command.create.handler:
    class: App\WalletManagement\Application\Command\CreateWalletHandler

  App\Shared\Infrastructure\BasicQueryBus:
    class: App\Shared\Infrastructure\BasicQueryBus
    arguments: [ ],
    calls:
      - map: [ 'App\WalletManagement\Application\Query\FindAllWalletsQuery', '@wallet.query.find_all.handler' ]
      - map: [ 'App\WalletManagement\Application\Query\GetBalanceQuery', '@wallet.query.get_balance.handler' ]

  wallet.query.find_all.handler:
    class: App\WalletManagement\Application\Query\FindAllWalletsHandler

  wallet.query.get_balance.handler:
    class: App\WalletManagement\Application\Query\GetBalanceHandler
